#!/command/with-contenv sh

if ! [ -f "/config/config.toml" ]
then
  echo "[default-confs] restoring default 'config.toml'."
  cp /config.default/config.toml /config/
fi

if ! [ -f "/config/defaults.ini" ]
then
  echo "[default-confs] restoring default 'defaults.ini'."
  cp /config.default/defaults.ini /config/
fi

if ! [ -f "/config/personal.ini" ]
then
  echo "[default-confs] restoring default 'personal.ini'."
  cp /config.default/personal.ini /config/
fi
